name: Build and Deploy FastAPI app

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-prep-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-prep-backend:latest


# NOT NEEDED IF NOT PUSHING TO AZURE

#      - name: Azure login
#        uses: azure/login@v2
#        with:
#          client-id: ${{ secrets.CONTAINERBACKEND_AZURE_CLIENT_ID }}
#          tenant-id: ${{ secrets.CONTAINERBACKEND_AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.CONTAINERBACKEND_AZURE_SUBSCRIPTION_ID }}
#
#      - name: Update container image
#        uses: azure/cli@v2
#        with:
#          inlineScript: |
#            az containerapp update \
#              --name container-backend \
#              --resource-group fullstack-2025-backend \
#              --image ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-2025-backend:latest
      


